In [4]:
import sys
sys.path.append('utilities/')
sys.path.append('source/')

In [17]:
import rbm
import RBM_utils
import Proteins_utils
import numpy
import pickle
import matplotlib.pyplot as plt

In [13]:
# load the model, which has been already trained
wwrbm = RBM_utils.loadRBM('policies/WW_RBM.pickle')

# load a set of natural sequences as data
seqs = Proteins_utils.load_FASTA('policies/WW_domain_MSA.fasta')

In [21]:
# The sequences are represented as a list of numbers (from 0 to 20),
# corresponding to the 20 amin-acids plus a gap character used for alignment.
seqs

array([[ 9, 12,  5, ...,  2,  6, 12],
       [20, 20,  4, ..., 16,  9, 12],
       [ 9, 12,  3, ...,  2,  6, 12],
       ...,
       [ 9, 12, 12, ..., 17,  2, 12],
       [ 9, 12,  0, ..., 11, 14, 12],
       [ 9, 12,  0, ...,  2,  2, 12]], dtype=int16)

In [22]:
# all sequences are of length 31
seqs[1]

array([20, 20,  4, 12, 18,  7,  3,  9,  8, 15, 15,  8, 16,  5, 13,  4, 19,
       19,  4, 11, 14, 11, 15, 11, 17, 15, 16, 19, 16,  9, 12],
      dtype=int16)

In [23]:
len(seqs[1])

31

In [16]:
# we can evaluate the energies of all the sequences, under the model.
# The energy is minus the score, so lower energies correspond to better sequences.
wwrbm.free_energy(seqs)

array([-256.00897, -224.40231, -246.14398, ..., -262.92142, -229.47812,
       -258.25323], dtype=float32)

In [20]:
# evaluate the energy a single sequence:
wwrbm.free_energy(seqs[1])

array([-224.40231], dtype=float32)